server:
  port: 9091
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
  servlet:
    context-path: /
  error:
    path: /error

# Spring Boot Admin 监控服务器端地址
# spring.boot.admin.client.url=http://localhost:9091
spring:
  application:
    name: monitor-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/server?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: server
    password: server
    hikari:
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: false
        order_by.default_null_ordering: last # 排序时 null 值置后
    druid:
      initial-size: 1
      min-idle: 5
      max-active: 50
      test-on-borrow: true
      validation-query: select 1
    # redis配置
    redis:
      # Redis数据库索引（默认为0）
      database: 1
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      # password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  boot:
    admin:
      client:
        url: http://localhost:9090
  thymeleaf:
    prefix: classpath:/thymeleaf/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html  

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: server-token
  # token有效期，单位s 默认30天, -1代表永不过期
  # timeout: 2592000
  timeout: -1
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

#token:
#  expire_time: 5000 # minutes
#  secret: "Hikari20210711"

logging:
  level:
    root: info # ?????? sql ????
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

#bezkoder.app.jwtSecret: tongchengzhaopin
#bezkoder.app.jwtExpirationMs: 86400000
wx:
  appid:
  appsecret:

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
